### ISSUE TITLE
Truffle compilator problem

### ISSUE THREAD

**Issue by JackBekket** [sonm-io/Factory#2]
When some of wallets-contracts is change it should recompile wallet contract itself AND factory contract because factory have import of this. 
BUT as factory contract itself doesn't change, truffle is not recompile it and you will use artefact with old wallet contract. 
For now to walkthrough this I just have to modified factory.sol every time as I change childe wallet contract. 
We should find better solution

**Comment by Sokel** [comment]
Done by 843be500ae3661b2f9f8af3bdde8cd7572e75b44
